from __future__ import annotations

import json
import re
from dataclasses import dataclass

from openai import OpenAI

from openai import RateLimitError, NotFoundError, BadRequestError

from .config import settings
from .generator import _openrouter, _FALLBACK_MODELS

_EVAL_PROMPT = """\
You are an objective RAG evaluation assistant. Given a question, the context chunks \
retrieved from a vector database, and the answer generated by an LLM, score each metric \
from 0.0 (worst) to 1.0 (best).

QUESTION:
{query}

RETRIEVED CONTEXT:
{context}

GENERATED ANSWER:
{answer}

Metrics to score:

1. groundedness (0-1)
   Are ALL factual claims in the answer directly supported by the retrieved context?
   1.0 = every claim is traceable to the context (no hallucination)
   0.0 = answer is entirely made up / contradicts the context

2. answer_relevance (0-1)
   Does the answer directly and completely address the question that was asked?
   1.0 = perfectly answers what was asked
   0.0 = completely off-topic or ignores the question

3. context_relevance (0-1)
   Are the retrieved context chunks actually useful for answering the question?
   1.0 = context is exactly what was needed
   0.0 = context is irrelevant to the question

Respond with ONLY a valid JSON object — no markdown fences, no extra text:
{{
  "groundedness": <float>,
  "answer_relevance": <float>,
  "context_relevance": <float>,
  "groundedness_reason": "<one concise sentence>",
  "answer_relevance_reason": "<one concise sentence>",
  "context_relevance_reason": "<one concise sentence>"
}}"""


@dataclass
class EvalScores:
    groundedness: float
    answer_relevance: float
    context_relevance: float
    groundedness_reason: str
    answer_relevance_reason: str
    context_relevance_reason: str

    @property
    def average(self) -> float:
        return round((self.groundedness + self.answer_relevance + self.context_relevance) / 3, 2)


def evaluate(query: str, answer: str, sources: list[dict]) -> EvalScores | None:
    """
    Score a RAG response on three dimensions using LLM-as-judge.

    Returns None silently if evaluation fails — it is always non-blocking
    so a scoring error never disrupts the main chat flow.
    """
    if not sources or not answer.strip():
        return None

    # Limit context to top 5 chunks to keep the eval prompt short
    context_parts = []
    for s in sources[:5]:
        meta = s["metadata"]
        context_parts.append(
            f"[Source: {meta['source_file']}, Page {meta['page']}]\n{meta['text']}"
        )
    context = "\n---\n".join(context_parts)

    prompt = _EVAL_PROMPT.format(query=query, context=context, answer=answer)

    seen: set[str] = set()
    models = [m for m in _FALLBACK_MODELS if not (m in seen or seen.add(m))]

    for model in models:
        try:
            completion = _openrouter.chat.completions.create(
                model=model,
                messages=[{"role": "user", "content": prompt}],
                temperature=0.0,
                max_tokens=512,
            )
            raw = completion.choices[0].message.content.strip()

            json_match = re.search(r"\{.*\}", raw, re.DOTALL)
            if not json_match:
                return None

            data = json.loads(json_match.group())

            return EvalScores(
                groundedness=max(0.0, min(1.0, float(data.get("groundedness", 0)))),
                answer_relevance=max(0.0, min(1.0, float(data.get("answer_relevance", 0)))),
                context_relevance=max(0.0, min(1.0, float(data.get("context_relevance", 0)))),
                groundedness_reason=data.get("groundedness_reason", ""),
                answer_relevance_reason=data.get("answer_relevance_reason", ""),
                context_relevance_reason=data.get("context_relevance_reason", ""),
            )
        except (RateLimitError, NotFoundError, BadRequestError):
            continue
        except Exception as e:
            print(f"[evaluator] exception: {e}")
            return None

    return None
